language: node_js
node_js:
- '6.1'
deploy:
  provider: npm
  email: 86287344@qq.com
  skip_cleanup: true
  api_key:
    secure: U/Z1eOPWa53CW0BxiDkMvL2IUQK87ouJJlom71nIT4uKGjconPh7itpeOR80s2eaNfi7sqbpl0BZduUX6O+m3vTaURHEup0B9gOx9YyegPiw2mdUVpECshs6rBO03Bprof6hVdY+WF6n2HbKZ3zsEXEqts3B6xXBIANUVV3ca8At8lUy3CxCiO7MNsS30MFcyRTQNOXybMMLjG1aWUnkR4wekEkR5gi9pVKNSiK71ju+iWQZbT75tnTtTjH5X3lxg5tPiBys+cvI1ZSeezKJiN3FDnUY0lfsr/3PAweHLcOOgOs2NPSRAeGNqaFyNqdJeVFPlUMztVq3KBI9eJZujrAt7cJ0Y45zWgWQcPUVpxl0YXM1QCa79CoR0rJ2QsqF1t1GuWbQgYd2v0L0ABr/yogKEKX2VY+ftHhRncv0zq8wNbBfQJxKafbKRVy50nsruHodtJAMm9f4pxauYpZ/wicDkfPWAkRExB4jGw+dEROOexAj26FLTmTYLQOlwvQF2DSOJzpZ+z7fJgf3XhsBtimfJSkzISvQ4Rzh2Xr8eeT0HDbpMB/1Om5hdgBley4yl6MAA80T9syrdJv77T2OjApx6/gI2jxxigJd36ISOtf2h6t3O8GqKSlDBVUkEYc843j1hTtigKUjsn0JQIuhXWrNyS8r8OZ8kZ5dGjILArA=
